#!/usr/bin/env bash

set -eu

export GO111MODULE=on
export GOFLAGS=-mod=readonly
export CGO_ENABLED=0

NAME=fcct

eval $(go env)
if [ -z ${BIN_PATH+a} ]; then
	BIN_PATH=${PWD}/bin/${GOARCH}
fi

echo "Building $NAME..."
go build -buildmode=pie -o ${BIN_PATH}/${NAME} internal/main.go
