#!/bin/bash
set -euo pipefail

export GO111MODULE=on

SRC=$(find . -name '*.go' -not -path "./vendor/*")

echo "checking gofmt"
res=$(gofmt -d $SRC)
echo "$res"
test -z "$res"

echo "Running tests"
go test ./... -cover

echo "Checking docs"
shopt -s nullglob
mkdir tmpdocs
trap 'rm -r tmpdocs' EXIT
# Create files-dir contents expected by configs
mkdir -p tmpdocs/files-dir/tree
touch tmpdocs/files-dir/local-file3

for doc in docs/*md
do
	echo "Checking $doc"
	# split each doc into a bunch of tmpfiles then run fcct on them
	sed -n '/^```yaml fedora-coreos-config/,/^```/ p' < ${doc} \
		| csplit - '/```yaml fedora-coreos-config/' '{*}' -z --prefix tmpdocs/tmpconfig -q

	for i in tmpdocs/tmpconfig*
	do
		cat "$i" | tail -n +2 | head -n -1 \
			| go run internal/main.go --strict --files-dir tmpdocs/files-dir > /dev/null \
			|| (cat -n "$i" && false)
	done
	rm -f tmpdocs/tmpconfig*
done

echo ok
